services:
  tomcat:
    build: .
    container_name: tomcat_container
    ports:
      - "8080:8080"  # Tomcat
      - "2222:22"    # SSH
    volumes:
      - ./webapps:/usr/local/tomcat/webapps  # Enlaza la carpeta local
    env_file: 
      - .env  # Archivo .env con las credenciales
    restart: unless-stopped
    command: ["/usr/local/tomcat/init.sh"]  # Descoméntalo si necesitas ejecutar un script personalizado