name: Docker Test and Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-docker-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker
        uses: docker/login-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: Dockerfile

      - name: Validate docker-compose.yml
        run: docker-compose config -q

      - name: Create .env file for testing
        run: |
          echo "SSH_USER=test" > .env
          echo "SSH_PASSWORD=testpass" >> .env
          echo "TOMCAT_USER=admin" >> .env
          echo "TOMCAT_PASSWORD=admin" >> .env

      - name: Build Docker image
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Verify container status
        run: |
          docker ps --filter "name=tomcat_container" --format "{{.Status}}" | grep -q "(healthy\|running)"

      - name: Test Tomcat HTTP connection
        run: |
          curl --retry 3 --retry-delay 5 --fail http://localhost:8080

      - name: Test SSH availability
        run: |
          nc -z -v -w5 localhost 2222

      - name: Cleanup
        if: always()
        run: docker-compose down --volumes --remove-orphans